engine_controller_node:
  ros__parameters:
    steps_to_full_circle: 240 # TODO(PriestOfAdanos): move to common_config.yml
    direction_pin: 20
    step_pin: 21
    prod_mode: True
    delay: .0208
    parent_frame_id: 'base_link'
    child_frame_id: 'top'
    translationXYZ: 
      - 0.0
      - 0.0
      - 0.0
      
scan_assembler_node:
  ros__parameters:
    steps_to_full_circle: 240
    make_clockwise_steps: True
    bags_path: '/bags'
    topics_to_subscribe:
      - 'sensor_msgs/msg/LaserScan'
      - 'tf2_msgs/msg/TFMessage'
      - 'tf2_msgs/msg/TFMessage'
