commons: &commons
  steps_to_full_circle: 240

engine_controller_node:
  ros__parameters:
    direction_pin: 20
    step_pin: 21
    prod_mode: True
    delay: .0208
    parent_frame_id: 'base_link'
    child_frame_id: 'top'
    translationXYZ: 
      - 0.0
      - 0.0
      - 0.0
    <<: *commons

scan_assembler_node:
  ros__parameters:
    make_clockwise_steps: True
    bags_path: '/bags'
    topics_to_subscribe:
      - 'sensor_msgs/msg/LaserScan'
      - 'tf2_msgs/msg/TFMessage'
      - 'tf2_msgs/msg/TFMessage'
    <<: *commons
