name: Docker build trigger

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  dispatch:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Invoke workflow in lc main repo
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Docker Image CI
        repo: PriestOfAdanos/lc
        token: ${{ secrets.PERSONAL_TOKEN }}
